//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvClientes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvClientes.IsrvClientes")]
    public interface IsrvClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/recClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/recClientes_ENTResponse")]
        System.Collections.Generic.List<Entidades.Clientes> recClientes_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/recClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/recClientes_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> recClientes_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/recClientesXId_ENT", ReplyAction="http://tempuri.org/IsrvClientes/recClientesXId_ENTResponse")]
        Entidades.Clientes recClientesXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/recClientesXId_ENT", ReplyAction="http://tempuri.org/IsrvClientes/recClientesXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Clientes> recClientesXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/insClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/insClientes_ENTResponse")]
        bool insClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/insClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/insClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> insClientes_ENTAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/modClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/modClientes_ENTResponse")]
        bool modClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/modClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/modClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> modClientes_ENTAsync(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/delClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/delClientes_ENTResponse")]
        bool delClientes_ENT(Entidades.Clientes pClientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvClientes/delClientes_ENT", ReplyAction="http://tempuri.org/IsrvClientes/delClientes_ENTResponse")]
        System.Threading.Tasks.Task<bool> delClientes_ENTAsync(Entidades.Clientes pClientes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvClientesChannel : mvcInterfazUsuario.srvClientes.IsrvClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvClientesClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvClientes.IsrvClientes>, mvcInterfazUsuario.srvClientes.IsrvClientes {
        
        public IsrvClientesClient() {
        }
        
        public IsrvClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Clientes> recClientes_ENT() {
            return base.Channel.recClientes_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> recClientes_ENTAsync() {
            return base.Channel.recClientes_ENTAsync();
        }
        
        public Entidades.Clientes recClientesXId_ENT(int pId) {
            return base.Channel.recClientesXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Clientes> recClientesXId_ENTAsync(int pId) {
            return base.Channel.recClientesXId_ENTAsync(pId);
        }
        
        public bool insClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.insClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> insClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.insClientes_ENTAsync(pClientes);
        }
        
        public bool modClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.modClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> modClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.modClientes_ENTAsync(pClientes);
        }
        
        public bool delClientes_ENT(Entidades.Clientes pClientes) {
            return base.Channel.delClientes_ENT(pClientes);
        }
        
        public System.Threading.Tasks.Task<bool> delClientes_ENTAsync(Entidades.Clientes pClientes) {
            return base.Channel.delClientes_ENTAsync(pClientes);
        }
    }
}
