//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvServicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvServicios.IsrvServicios")]
    public interface IsrvServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/recServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/recServicios_ENTResponse")]
        System.Collections.Generic.List<Entidades.Servicios> recServicios_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/recServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/recServicios_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Servicios>> recServicios_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/recServiciosXId_ENT", ReplyAction="http://tempuri.org/IsrvServicios/recServiciosXId_ENTResponse")]
        Entidades.Servicios recServiciosXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/recServiciosXId_ENT", ReplyAction="http://tempuri.org/IsrvServicios/recServiciosXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Servicios> recServiciosXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/insServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/insServicios_ENTResponse")]
        bool insServicios_ENT(Entidades.Servicios pServicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/insServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/insServicios_ENTResponse")]
        System.Threading.Tasks.Task<bool> insServicios_ENTAsync(Entidades.Servicios pServicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/modServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/modServicios_ENTResponse")]
        bool modServicios_ENT(Entidades.Servicios pServicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/modServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/modServicios_ENTResponse")]
        System.Threading.Tasks.Task<bool> modServicios_ENTAsync(Entidades.Servicios pServicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/delServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/delServicios_ENTResponse")]
        bool delServicios_ENT(Entidades.Servicios pServicios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvServicios/delServicios_ENT", ReplyAction="http://tempuri.org/IsrvServicios/delServicios_ENTResponse")]
        System.Threading.Tasks.Task<bool> delServicios_ENTAsync(Entidades.Servicios pServicios);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvServiciosChannel : mvcInterfazUsuario.srvServicios.IsrvServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvServiciosClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvServicios.IsrvServicios>, mvcInterfazUsuario.srvServicios.IsrvServicios {
        
        public IsrvServiciosClient() {
        }
        
        public IsrvServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Servicios> recServicios_ENT() {
            return base.Channel.recServicios_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Servicios>> recServicios_ENTAsync() {
            return base.Channel.recServicios_ENTAsync();
        }
        
        public Entidades.Servicios recServiciosXId_ENT(int pId) {
            return base.Channel.recServiciosXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Servicios> recServiciosXId_ENTAsync(int pId) {
            return base.Channel.recServiciosXId_ENTAsync(pId);
        }
        
        public bool insServicios_ENT(Entidades.Servicios pServicios) {
            return base.Channel.insServicios_ENT(pServicios);
        }
        
        public System.Threading.Tasks.Task<bool> insServicios_ENTAsync(Entidades.Servicios pServicios) {
            return base.Channel.insServicios_ENTAsync(pServicios);
        }
        
        public bool modServicios_ENT(Entidades.Servicios pServicios) {
            return base.Channel.modServicios_ENT(pServicios);
        }
        
        public System.Threading.Tasks.Task<bool> modServicios_ENTAsync(Entidades.Servicios pServicios) {
            return base.Channel.modServicios_ENTAsync(pServicios);
        }
        
        public bool delServicios_ENT(Entidades.Servicios pServicios) {
            return base.Channel.delServicios_ENT(pServicios);
        }
        
        public System.Threading.Tasks.Task<bool> delServicios_ENTAsync(Entidades.Servicios pServicios) {
            return base.Channel.delServicios_ENTAsync(pServicios);
        }
    }
}
