//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvSeguridad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvSeguridad.IsrvSeguridad")]
    public interface IsrvSeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recUsuarioResponse")]
        Entidades.TUSR_USUARIOS recUsuario(string pUsrLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSeguridad/recUsuario", ReplyAction="http://tempuri.org/IsrvSeguridad/recUsuarioResponse")]
        System.Threading.Tasks.Task<Entidades.TUSR_USUARIOS> recUsuarioAsync(string pUsrLogin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvSeguridadChannel : mvcInterfazUsuario.srvSeguridad.IsrvSeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvSeguridadClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvSeguridad.IsrvSeguridad>, mvcInterfazUsuario.srvSeguridad.IsrvSeguridad {
        
        public IsrvSeguridadClient() {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.TUSR_USUARIOS recUsuario(string pUsrLogin) {
            return base.Channel.recUsuario(pUsrLogin);
        }
        
        public System.Threading.Tasks.Task<Entidades.TUSR_USUARIOS> recUsuarioAsync(string pUsrLogin) {
            return base.Channel.recUsuarioAsync(pUsrLogin);
        }
    }
}
