//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvDiagnostico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvDiagnostico.IsrvDiagnostico")]
    public interface IsrvDiagnostico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnósticos_ENTResponse")]
        System.Collections.Generic.List<Entidades.Diagnósticos> recDiagnósticos_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Diagnósticos>> recDiagnósticos_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnósticosXId_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnósticosXId_ENTResponse")]
        Entidades.Diagnósticos recDiagnósticosXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnósticosXId_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnósticosXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Diagnósticos> recDiagnósticosXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/insDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/insDiagnósticos_ENTResponse")]
        bool insDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/insDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/insDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> insDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/modDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/modDiagnósticos_ENTResponse")]
        bool modDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/modDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/modDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> modDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/delDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/delDiagnósticos_ENTResponse")]
        bool delDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/delDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnostico/delDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> delDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvDiagnosticoChannel : mvcInterfazUsuario.srvDiagnostico.IsrvDiagnostico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvDiagnosticoClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvDiagnostico.IsrvDiagnostico>, mvcInterfazUsuario.srvDiagnostico.IsrvDiagnostico {
        
        public IsrvDiagnosticoClient() {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Diagnósticos> recDiagnósticos_ENT() {
            return base.Channel.recDiagnósticos_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Diagnósticos>> recDiagnósticos_ENTAsync() {
            return base.Channel.recDiagnósticos_ENTAsync();
        }
        
        public Entidades.Diagnósticos recDiagnósticosXId_ENT(int pId) {
            return base.Channel.recDiagnósticosXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Diagnósticos> recDiagnósticosXId_ENTAsync(int pId) {
            return base.Channel.recDiagnósticosXId_ENTAsync(pId);
        }
        
        public bool insDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.insDiagnósticos_ENT(pDiagnósticos);
        }
        
        public System.Threading.Tasks.Task<bool> insDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.insDiagnósticos_ENTAsync(pDiagnósticos);
        }
        
        public bool modDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.modDiagnósticos_ENT(pDiagnósticos);
        }
        
        public System.Threading.Tasks.Task<bool> modDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.modDiagnósticos_ENTAsync(pDiagnósticos);
        }
        
        public bool delDiagnósticos_ENT(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.delDiagnósticos_ENT(pDiagnósticos);
        }
        
        public System.Threading.Tasks.Task<bool> delDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnósticos) {
            return base.Channel.delDiagnósticos_ENTAsync(pDiagnósticos);
        }
    }
}
