//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvCountryRegion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvCountryRegion.IsrvCountryRegion")]
    public interface IsrvCountryRegion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegion_ENTResponse")]
        System.Collections.Generic.List<Entidades.CountryRegion> recCountryRegion_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegion_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.CountryRegion>> recCountryRegion_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_ENTResponse")]
        Entidades.CountryRegion recCountryRegionXId_ENT(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.CountryRegion> recCountryRegionXId_ENTAsync(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/insCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/insCountryRegion_ENTResponse")]
        bool insCountryRegion_ENT(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/insCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/insCountryRegion_ENTResponse")]
        System.Threading.Tasks.Task<bool> insCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/modCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/modCountryRegion_ENTResponse")]
        bool modCountryRegion_ENT(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/modCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/modCountryRegion_ENTResponse")]
        System.Threading.Tasks.Task<bool> modCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/delCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/delCountryRegion_ENTResponse")]
        bool delCountryRegion_ENT(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/delCountryRegion_ENT", ReplyAction="http://tempuri.org/IsrvCountryRegion/delCountryRegion_ENTResponse")]
        System.Threading.Tasks.Task<bool> delCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegion_PAResponse")]
        System.Collections.Generic.List<Entidades.recCountryRegions_Result> recCountryRegion_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegion_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recCountryRegions_Result>> recCountryRegion_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_PAResponse")]
        Entidades.recCountryRegionsxId_Result recCountryRegionXId_PA(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/recCountryRegionXId_PAResponse")]
        System.Threading.Tasks.Task<Entidades.recCountryRegionsxId_Result> recCountryRegionXId_PAAsync(string pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/insCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/insCountryRegion_PAResponse")]
        bool insCountryRegion_PA(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/insCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/insCountryRegion_PAResponse")]
        System.Threading.Tasks.Task<bool> insCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/modCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/modCountryRegion_PAResponse")]
        bool modCountryRegion_PA(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/modCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/modCountryRegion_PAResponse")]
        System.Threading.Tasks.Task<bool> modCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/delCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/delCountryRegion_PAResponse")]
        bool delCountryRegion_PA(Entidades.CountryRegion pCountryRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCountryRegion/delCountryRegion_PA", ReplyAction="http://tempuri.org/IsrvCountryRegion/delCountryRegion_PAResponse")]
        System.Threading.Tasks.Task<bool> delCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvCountryRegionChannel : mvcInterfazUsuario.srvCountryRegion.IsrvCountryRegion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvCountryRegionClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvCountryRegion.IsrvCountryRegion>, mvcInterfazUsuario.srvCountryRegion.IsrvCountryRegion {
        
        public IsrvCountryRegionClient() {
        }
        
        public IsrvCountryRegionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvCountryRegionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCountryRegionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCountryRegionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.CountryRegion> recCountryRegion_ENT() {
            return base.Channel.recCountryRegion_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.CountryRegion>> recCountryRegion_ENTAsync() {
            return base.Channel.recCountryRegion_ENTAsync();
        }
        
        public Entidades.CountryRegion recCountryRegionXId_ENT(string pId) {
            return base.Channel.recCountryRegionXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.CountryRegion> recCountryRegionXId_ENTAsync(string pId) {
            return base.Channel.recCountryRegionXId_ENTAsync(pId);
        }
        
        public bool insCountryRegion_ENT(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.insCountryRegion_ENT(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> insCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.insCountryRegion_ENTAsync(pCountryRegion);
        }
        
        public bool modCountryRegion_ENT(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.modCountryRegion_ENT(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> modCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.modCountryRegion_ENTAsync(pCountryRegion);
        }
        
        public bool delCountryRegion_ENT(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.delCountryRegion_ENT(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> delCountryRegion_ENTAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.delCountryRegion_ENTAsync(pCountryRegion);
        }
        
        public System.Collections.Generic.List<Entidades.recCountryRegions_Result> recCountryRegion_PA() {
            return base.Channel.recCountryRegion_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.recCountryRegions_Result>> recCountryRegion_PAAsync() {
            return base.Channel.recCountryRegion_PAAsync();
        }
        
        public Entidades.recCountryRegionsxId_Result recCountryRegionXId_PA(string pId) {
            return base.Channel.recCountryRegionXId_PA(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.recCountryRegionsxId_Result> recCountryRegionXId_PAAsync(string pId) {
            return base.Channel.recCountryRegionXId_PAAsync(pId);
        }
        
        public bool insCountryRegion_PA(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.insCountryRegion_PA(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> insCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.insCountryRegion_PAAsync(pCountryRegion);
        }
        
        public bool modCountryRegion_PA(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.modCountryRegion_PA(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> modCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.modCountryRegion_PAAsync(pCountryRegion);
        }
        
        public bool delCountryRegion_PA(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.delCountryRegion_PA(pCountryRegion);
        }
        
        public System.Threading.Tasks.Task<bool> delCountryRegion_PAAsync(Entidades.CountryRegion pCountryRegion) {
            return base.Channel.delCountryRegion_PAAsync(pCountryRegion);
        }
    }
}
