//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvCitas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvCitas.IsrvCitas")]
    public interface IsrvCitas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/recCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/recCitas_ENTResponse")]
        System.Collections.Generic.List<Entidades.Citas> recCitas_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/recCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/recCitas_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Citas>> recCitas_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/recCitasXId_ENT", ReplyAction="http://tempuri.org/IsrvCitas/recCitasXId_ENTResponse")]
        Entidades.Citas recCitasXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/recCitasXId_ENT", ReplyAction="http://tempuri.org/IsrvCitas/recCitasXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Citas> recCitasXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/insCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/insCitas_ENTResponse")]
        bool insCitas_ENT(Entidades.Citas pCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/insCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/insCitas_ENTResponse")]
        System.Threading.Tasks.Task<bool> insCitas_ENTAsync(Entidades.Citas pCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/modCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/modCitas_ENTResponse")]
        bool modCitas_ENT(Entidades.Citas pCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/modCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/modCitas_ENTResponse")]
        System.Threading.Tasks.Task<bool> modCitas_ENTAsync(Entidades.Citas pCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/delCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/delCitas_ENTResponse")]
        bool delCitas_ENT(Entidades.Citas pCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCitas/delCitas_ENT", ReplyAction="http://tempuri.org/IsrvCitas/delCitas_ENTResponse")]
        System.Threading.Tasks.Task<bool> delCitas_ENTAsync(Entidades.Citas pCitas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvCitasChannel : mvcInterfazUsuario.srvCitas.IsrvCitas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvCitasClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvCitas.IsrvCitas>, mvcInterfazUsuario.srvCitas.IsrvCitas {
        
        public IsrvCitasClient() {
        }
        
        public IsrvCitasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvCitasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCitasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCitasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Citas> recCitas_ENT() {
            return base.Channel.recCitas_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Citas>> recCitas_ENTAsync() {
            return base.Channel.recCitas_ENTAsync();
        }
        
        public Entidades.Citas recCitasXId_ENT(int pId) {
            return base.Channel.recCitasXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Citas> recCitasXId_ENTAsync(int pId) {
            return base.Channel.recCitasXId_ENTAsync(pId);
        }
        
        public bool insCitas_ENT(Entidades.Citas pCitas) {
            return base.Channel.insCitas_ENT(pCitas);
        }
        
        public System.Threading.Tasks.Task<bool> insCitas_ENTAsync(Entidades.Citas pCitas) {
            return base.Channel.insCitas_ENTAsync(pCitas);
        }
        
        public bool modCitas_ENT(Entidades.Citas pCitas) {
            return base.Channel.modCitas_ENT(pCitas);
        }
        
        public System.Threading.Tasks.Task<bool> modCitas_ENTAsync(Entidades.Citas pCitas) {
            return base.Channel.modCitas_ENTAsync(pCitas);
        }
        
        public bool delCitas_ENT(Entidades.Citas pCitas) {
            return base.Channel.delCitas_ENT(pCitas);
        }
        
        public System.Threading.Tasks.Task<bool> delCitas_ENTAsync(Entidades.Citas pCitas) {
            return base.Channel.delCitas_ENTAsync(pCitas);
        }
    }
}
