//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvFacturacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvFacturacion.IsrvFacturacion")]
    public interface IsrvFacturacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/recFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/recFacturacion_ENTResponse")]
        System.Collections.Generic.List<Entidades.Facturacion> recFacturacion_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/recFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/recFacturacion_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Facturacion>> recFacturacion_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/recFacturacionXId_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/recFacturacionXId_ENTResponse")]
        Entidades.Facturacion recFacturacionXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/recFacturacionXId_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/recFacturacionXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Facturacion> recFacturacionXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/insFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/insFacturacion_ENTResponse")]
        bool insFacturacion_ENT(Entidades.Facturacion pFacturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/insFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/insFacturacion_ENTResponse")]
        System.Threading.Tasks.Task<bool> insFacturacion_ENTAsync(Entidades.Facturacion pFacturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/modFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/modFacturacion_ENTResponse")]
        bool modFacturacion_ENT(Entidades.Facturacion pFacturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/modFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/modFacturacion_ENTResponse")]
        System.Threading.Tasks.Task<bool> modFacturacion_ENTAsync(Entidades.Facturacion pFacturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/delFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/delFacturacion_ENTResponse")]
        bool delFacturacion_ENT(Entidades.Facturacion pFacturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvFacturacion/delFacturacion_ENT", ReplyAction="http://tempuri.org/IsrvFacturacion/delFacturacion_ENTResponse")]
        System.Threading.Tasks.Task<bool> delFacturacion_ENTAsync(Entidades.Facturacion pFacturacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvFacturacionChannel : mvcInterfazUsuario.srvFacturacion.IsrvFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvFacturacionClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvFacturacion.IsrvFacturacion>, mvcInterfazUsuario.srvFacturacion.IsrvFacturacion {
        
        public IsrvFacturacionClient() {
        }
        
        public IsrvFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Facturacion> recFacturacion_ENT() {
            return base.Channel.recFacturacion_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Facturacion>> recFacturacion_ENTAsync() {
            return base.Channel.recFacturacion_ENTAsync();
        }
        
        public Entidades.Facturacion recFacturacionXId_ENT(int pId) {
            return base.Channel.recFacturacionXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Facturacion> recFacturacionXId_ENTAsync(int pId) {
            return base.Channel.recFacturacionXId_ENTAsync(pId);
        }
        
        public bool insFacturacion_ENT(Entidades.Facturacion pFacturacion) {
            return base.Channel.insFacturacion_ENT(pFacturacion);
        }
        
        public System.Threading.Tasks.Task<bool> insFacturacion_ENTAsync(Entidades.Facturacion pFacturacion) {
            return base.Channel.insFacturacion_ENTAsync(pFacturacion);
        }
        
        public bool modFacturacion_ENT(Entidades.Facturacion pFacturacion) {
            return base.Channel.modFacturacion_ENT(pFacturacion);
        }
        
        public System.Threading.Tasks.Task<bool> modFacturacion_ENTAsync(Entidades.Facturacion pFacturacion) {
            return base.Channel.modFacturacion_ENTAsync(pFacturacion);
        }
        
        public bool delFacturacion_ENT(Entidades.Facturacion pFacturacion) {
            return base.Channel.delFacturacion_ENT(pFacturacion);
        }
        
        public System.Threading.Tasks.Task<bool> delFacturacion_ENTAsync(Entidades.Facturacion pFacturacion) {
            return base.Channel.delFacturacion_ENTAsync(pFacturacion);
        }
    }
}
