//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class AWEntidades : DbContext
    {
        public AWEntidades()
            : base("name=AWEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AWBuildVersion> AWBuildVersion { get; set; }
        public virtual DbSet<DatabaseLog> DatabaseLog { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<DemoSalesOrderDetailSeed> DemoSalesOrderDetailSeed { get; set; }
        public virtual DbSet<DemoSalesOrderHeaderSeed> DemoSalesOrderHeaderSeed { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Temporal> Employee_Temporal { get; set; }
        public virtual DbSet<EmployeeDepartmentHistory> EmployeeDepartmentHistory { get; set; }
        public virtual DbSet<EmployeePayHistory> EmployeePayHistory { get; set; }
        public virtual DbSet<JobCandidate> JobCandidate { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<BusinessEntity> BusinessEntity { get; set; }
        public virtual DbSet<BusinessEntityAddress> BusinessEntityAddress { get; set; }
        public virtual DbSet<BusinessEntityContact> BusinessEntityContact { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<CountryRegion> CountryRegion { get; set; }
        public virtual DbSet<EmailAddress> EmailAddress { get; set; }
        public virtual DbSet<Password> Password { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Person_json> Person_json { get; set; }
        public virtual DbSet<Person_Temporal> Person_Temporal { get; set; }
        public virtual DbSet<PersonPhone> PersonPhone { get; set; }
        public virtual DbSet<PhoneNumberType> PhoneNumberType { get; set; }
        public virtual DbSet<StateProvince> StateProvince { get; set; }
        public virtual DbSet<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual DbSet<Culture> Culture { get; set; }
        public virtual DbSet<Illustration> Illustration { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_inmem> Product_inmem { get; set; }
        public virtual DbSet<Product_ondisk> Product_ondisk { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public virtual DbSet<ProductDescription> ProductDescription { get; set; }
        public virtual DbSet<ProductInventory> ProductInventory { get; set; }
        public virtual DbSet<ProductListPriceHistory> ProductListPriceHistory { get; set; }
        public virtual DbSet<ProductModel> ProductModel { get; set; }
        public virtual DbSet<ProductModelIllustration> ProductModelIllustration { get; set; }
        public virtual DbSet<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCulture { get; set; }
        public virtual DbSet<ProductPhoto> ProductPhoto { get; set; }
        public virtual DbSet<ProductProductPhoto> ProductProductPhoto { get; set; }
        public virtual DbSet<ProductReview> ProductReview { get; set; }
        public virtual DbSet<ProductSubcategory> ProductSubcategory { get; set; }
        public virtual DbSet<ScrapReason> ScrapReason { get; set; }
        public virtual DbSet<TransactionHistory> TransactionHistory { get; set; }
        public virtual DbSet<TransactionHistoryArchive> TransactionHistoryArchive { get; set; }
        public virtual DbSet<UnitMeasure> UnitMeasure { get; set; }
        public virtual DbSet<WorkOrder> WorkOrder { get; set; }
        public virtual DbSet<WorkOrderRouting> WorkOrderRouting { get; set; }
        public virtual DbSet<ProductVendor> ProductVendor { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public virtual DbSet<PurchaseOrderHeader> PurchaseOrderHeader { get; set; }
        public virtual DbSet<ShipMethod> ShipMethod { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<CountryRegionCurrency> CountryRegionCurrency { get; set; }
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRate { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<OrderTracking> OrderTracking { get; set; }
        public virtual DbSet<PersonCreditCard> PersonCreditCard { get; set; }
        public virtual DbSet<SalesOrder_json> SalesOrder_json { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetail { get; set; }
        public virtual DbSet<SalesOrderDetail_inmem> SalesOrderDetail_inmem { get; set; }
        public virtual DbSet<SalesOrderDetail_ondisk> SalesOrderDetail_ondisk { get; set; }
        public virtual DbSet<SalesOrderHeader> SalesOrderHeader { get; set; }
        public virtual DbSet<SalesOrderHeader_inmem> SalesOrderHeader_inmem { get; set; }
        public virtual DbSet<SalesOrderHeader_ondisk> SalesOrderHeader_ondisk { get; set; }
        public virtual DbSet<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReason { get; set; }
        public virtual DbSet<SalesPerson> SalesPerson { get; set; }
        public virtual DbSet<SalesPersonQuotaHistory> SalesPersonQuotaHistory { get; set; }
        public virtual DbSet<SalesReason> SalesReason { get; set; }
        public virtual DbSet<SalesTaxRate> SalesTaxRate { get; set; }
        public virtual DbSet<SalesTerritory> SalesTerritory { get; set; }
        public virtual DbSet<SalesTerritoryHistory> SalesTerritoryHistory { get; set; }
        public virtual DbSet<ShoppingCartItem> ShoppingCartItem { get; set; }
        public virtual DbSet<SpecialOffer> SpecialOffer { get; set; }
        public virtual DbSet<SpecialOffer_inmem> SpecialOffer_inmem { get; set; }
        public virtual DbSet<SpecialOffer_ondisk> SpecialOffer_ondisk { get; set; }
        public virtual DbSet<SpecialOfferProduct> SpecialOfferProduct { get; set; }
        public virtual DbSet<SpecialOfferProduct_inmem> SpecialOfferProduct_inmem { get; set; }
        public virtual DbSet<SpecialOfferProduct_ondisk> SpecialOfferProduct_ondisk { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<TrackingEvent> TrackingEvent { get; set; }
        public virtual DbSet<Employee_Temporal_History> Employee_Temporal_History { get; set; }
        public virtual DbSet<Person_Temporal_History> Person_Temporal_History { get; set; }
        public virtual DbSet<ProductDocument> ProductDocument { get; set; }
        public virtual DbSet<CustomerPII> CustomerPII { get; set; }
        public virtual DbSet<vEmployee> vEmployee { get; set; }
        public virtual DbSet<vEmployeeDepartment> vEmployeeDepartment { get; set; }
        public virtual DbSet<vEmployeeDepartmentHistory> vEmployeeDepartmentHistory { get; set; }
        public virtual DbSet<vEmployeePersonTemporalInfo> vEmployeePersonTemporalInfo { get; set; }
        public virtual DbSet<vJobCandidate> vJobCandidate { get; set; }
        public virtual DbSet<vJobCandidateEducation> vJobCandidateEducation { get; set; }
        public virtual DbSet<vJobCandidateEmployment> vJobCandidateEmployment { get; set; }
        public virtual DbSet<vAdditionalContactInfo> vAdditionalContactInfo { get; set; }
        public virtual DbSet<vStateProvinceCountryRegion> vStateProvinceCountryRegion { get; set; }
        public virtual DbSet<vProductAndDescription> vProductAndDescription { get; set; }
        public virtual DbSet<vProductModelCatalogDescription> vProductModelCatalogDescription { get; set; }
        public virtual DbSet<vProductModelInstructions> vProductModelInstructions { get; set; }
        public virtual DbSet<vVendorWithAddresses> vVendorWithAddresses { get; set; }
        public virtual DbSet<vVendorWithContacts> vVendorWithContacts { get; set; }
        public virtual DbSet<vIndividualCustomer> vIndividualCustomer { get; set; }
        public virtual DbSet<vPersonDemographics> vPersonDemographics { get; set; }
        public virtual DbSet<vSalesPerson> vSalesPerson { get; set; }
        public virtual DbSet<vSalesPersonSalesByFiscalYears> vSalesPersonSalesByFiscalYears { get; set; }
        public virtual DbSet<vStoreWithAddresses> vStoreWithAddresses { get; set; }
        public virtual DbSet<vStoreWithContacts> vStoreWithContacts { get; set; }
        public virtual DbSet<vStoreWithDemographics> vStoreWithDemographics { get; set; }
    
        [DbFunction("AWEntidades", "ufnGetContactInformation")]
        public virtual IQueryable<ufnGetContactInformation_Result> ufnGetContactInformation(Nullable<int> personID)
        {
            var personIDParameter = personID.HasValue ?
                new ObjectParameter("PersonID", personID) :
                new ObjectParameter("PersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufnGetContactInformation_Result>("[AWEntidades].[ufnGetContactInformation](@PersonID)", personIDParameter);
        }
    
        [DbFunction("AWEntidades", "vSalesOrderDetail_extended_inmem")]
        public virtual IQueryable<vSalesOrderDetail_extended_inmem_Result> vSalesOrderDetail_extended_inmem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<vSalesOrderDetail_extended_inmem_Result>("[AWEntidades].[vSalesOrderDetail_extended_inmem]()");
        }
    
        [DbFunction("AWEntidades", "vSalesOrderHeader_extended_inmem")]
        public virtual IQueryable<vSalesOrderHeader_extended_inmem_Result> vSalesOrderHeader_extended_inmem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<vSalesOrderHeader_extended_inmem_Result>("[AWEntidades].[vSalesOrderHeader_extended_inmem]()");
        }
    
        [DbFunction("AWEntidades", "customerAccessPredicate")]
        public virtual IQueryable<customerAccessPredicate_Result> customerAccessPredicate(Nullable<int> territoryID)
        {
            var territoryIDParameter = territoryID.HasValue ?
                new ObjectParameter("TerritoryID", territoryID) :
                new ObjectParameter("TerritoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<customerAccessPredicate_Result>("[AWEntidades].[customerAccessPredicate](@TerritoryID)", territoryIDParameter);
        }
    
        public virtual int delCountryRegions(string countryRegionCode)
        {
            var countryRegionCodeParameter = countryRegionCode != null ?
                new ObjectParameter("CountryRegionCode", countryRegionCode) :
                new ObjectParameter("CountryRegionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCountryRegions", countryRegionCodeParameter);
        }
    
        public virtual int delCulture(string cultureID)
        {
            var cultureIDParameter = cultureID != null ?
                new ObjectParameter("CultureID", cultureID) :
                new ObjectParameter("CultureID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCulture", cultureIDParameter);
        }
    
        public virtual int delCurrency(string currencyCode)
        {
            var currencyCodeParameter = currencyCode != null ?
                new ObjectParameter("CurrencyCode", currencyCode) :
                new ObjectParameter("CurrencyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delCurrency", currencyCodeParameter);
        }
    
        public virtual int delDepartment(Nullable<short> departmentID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delDepartment", departmentIDParameter);
        }
    
        public virtual int delSalesReason(Nullable<int> salesReasonID)
        {
            var salesReasonIDParameter = salesReasonID.HasValue ?
                new ObjectParameter("SalesReasonID", salesReasonID) :
                new ObjectParameter("SalesReasonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delSalesReason", salesReasonIDParameter);
        }
    
        public virtual int delUnitMeasure(string unitMeasureCode)
        {
            var unitMeasureCodeParameter = unitMeasureCode != null ?
                new ObjectParameter("UnitMeasureCode", unitMeasureCode) :
                new ObjectParameter("UnitMeasureCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delUnitMeasure", unitMeasureCodeParameter);
        }
    
        public virtual int insCountryRegions(string countryRegionCode, string name)
        {
            var countryRegionCodeParameter = countryRegionCode != null ?
                new ObjectParameter("CountryRegionCode", countryRegionCode) :
                new ObjectParameter("CountryRegionCode", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insCountryRegions", countryRegionCodeParameter, nameParameter);
        }
    
        public virtual int insCulture(string cultureID, string cname)
        {
            var cultureIDParameter = cultureID != null ?
                new ObjectParameter("CultureID", cultureID) :
                new ObjectParameter("CultureID", typeof(string));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("Cname", cname) :
                new ObjectParameter("Cname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insCulture", cultureIDParameter, cnameParameter);
        }
    
        public virtual int insCurrency(string currencyCode, string cNAME)
        {
            var currencyCodeParameter = currencyCode != null ?
                new ObjectParameter("CurrencyCode", currencyCode) :
                new ObjectParameter("CurrencyCode", typeof(string));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insCurrency", currencyCodeParameter, cNAMEParameter);
        }
    
        public virtual int insDepartment(string nomDpto, string groupName)
        {
            var nomDptoParameter = nomDpto != null ?
                new ObjectParameter("NomDpto", nomDpto) :
                new ObjectParameter("NomDpto", typeof(string));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insDepartment", nomDptoParameter, groupNameParameter);
        }
    
        public virtual int insSalesReason(string cName, string reasonType)
        {
            var cNameParameter = cName != null ?
                new ObjectParameter("CName", cName) :
                new ObjectParameter("CName", typeof(string));
    
            var reasonTypeParameter = reasonType != null ?
                new ObjectParameter("ReasonType", reasonType) :
                new ObjectParameter("ReasonType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insSalesReason", cNameParameter, reasonTypeParameter);
        }
    
        public virtual int insUnitMeasure(string unitMeasureCode, string cNAME)
        {
            var unitMeasureCodeParameter = unitMeasureCode != null ?
                new ObjectParameter("UnitMeasureCode", unitMeasureCode) :
                new ObjectParameter("UnitMeasureCode", typeof(string));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insUnitMeasure", unitMeasureCodeParameter, cNAMEParameter);
        }
    
        public virtual int modCountryRegions(string countryRegionCode, string name)
        {
            var countryRegionCodeParameter = countryRegionCode != null ?
                new ObjectParameter("CountryRegionCode", countryRegionCode) :
                new ObjectParameter("CountryRegionCode", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modCountryRegions", countryRegionCodeParameter, nameParameter);
        }
    
        public virtual int modCulture(string cultureID, string cname)
        {
            var cultureIDParameter = cultureID != null ?
                new ObjectParameter("CultureID", cultureID) :
                new ObjectParameter("CultureID", typeof(string));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("Cname", cname) :
                new ObjectParameter("Cname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modCulture", cultureIDParameter, cnameParameter);
        }
    
        public virtual int modCurrency(string currencyCode, string cNAME)
        {
            var currencyCodeParameter = currencyCode != null ?
                new ObjectParameter("CurrencyCode", currencyCode) :
                new ObjectParameter("CurrencyCode", typeof(string));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modCurrency", currencyCodeParameter, cNAMEParameter);
        }
    
        public virtual int modDepartment(Nullable<short> departmentID, string nomDpto, string groupName)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(short));
    
            var nomDptoParameter = nomDpto != null ?
                new ObjectParameter("NomDpto", nomDpto) :
                new ObjectParameter("NomDpto", typeof(string));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modDepartment", departmentIDParameter, nomDptoParameter, groupNameParameter);
        }
    
        public virtual int modSalesReason(Nullable<int> salesReasonID, string cName, string reasonType)
        {
            var salesReasonIDParameter = salesReasonID.HasValue ?
                new ObjectParameter("SalesReasonID", salesReasonID) :
                new ObjectParameter("SalesReasonID", typeof(int));
    
            var cNameParameter = cName != null ?
                new ObjectParameter("CName", cName) :
                new ObjectParameter("CName", typeof(string));
    
            var reasonTypeParameter = reasonType != null ?
                new ObjectParameter("ReasonType", reasonType) :
                new ObjectParameter("ReasonType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modSalesReason", salesReasonIDParameter, cNameParameter, reasonTypeParameter);
        }
    
        public virtual int modUnitMeasure(string unitMeasureCode, string cNAME)
        {
            var unitMeasureCodeParameter = unitMeasureCode != null ?
                new ObjectParameter("UnitMeasureCode", unitMeasureCode) :
                new ObjectParameter("UnitMeasureCode", typeof(string));
    
            var cNAMEParameter = cNAME != null ?
                new ObjectParameter("CNAME", cNAME) :
                new ObjectParameter("CNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modUnitMeasure", unitMeasureCodeParameter, cNAMEParameter);
        }
    
        public virtual int PA_delCreditCard(Nullable<int> creditCardID)
        {
            var creditCardIDParameter = creditCardID.HasValue ?
                new ObjectParameter("CreditCardID", creditCardID) :
                new ObjectParameter("CreditCardID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delCreditCard", creditCardIDParameter);
        }
    
        public virtual int PA_delUbicacion(Nullable<short> locationID)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delUbicacion", locationIDParameter);
        }
    
        public virtual int PA_insCreditCard(string cardType, string cardNumber, Nullable<byte> expMonth, Nullable<short> expYear)
        {
            var cardTypeParameter = cardType != null ?
                new ObjectParameter("CardType", cardType) :
                new ObjectParameter("CardType", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(string));
    
            var expMonthParameter = expMonth.HasValue ?
                new ObjectParameter("ExpMonth", expMonth) :
                new ObjectParameter("ExpMonth", typeof(byte));
    
            var expYearParameter = expYear.HasValue ?
                new ObjectParameter("ExpYear", expYear) :
                new ObjectParameter("ExpYear", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insCreditCard", cardTypeParameter, cardNumberParameter, expMonthParameter, expYearParameter);
        }
    
        public virtual int PA_insUbicacion(string nombre, Nullable<decimal> costo, Nullable<decimal> disponibilidad, Nullable<System.DateTime> fecModifica)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("Costo", costo) :
                new ObjectParameter("Costo", typeof(decimal));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(decimal));
    
            var fecModificaParameter = fecModifica.HasValue ?
                new ObjectParameter("FecModifica", fecModifica) :
                new ObjectParameter("FecModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insUbicacion", nombreParameter, costoParameter, disponibilidadParameter, fecModificaParameter);
        }
    
        public virtual int PA_modCreditCard(Nullable<int> creditCardID, string cardType, string cardNumber, Nullable<byte> expMonth, Nullable<short> expYear)
        {
            var creditCardIDParameter = creditCardID.HasValue ?
                new ObjectParameter("CreditCardID", creditCardID) :
                new ObjectParameter("CreditCardID", typeof(int));
    
            var cardTypeParameter = cardType != null ?
                new ObjectParameter("CardType", cardType) :
                new ObjectParameter("CardType", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(string));
    
            var expMonthParameter = expMonth.HasValue ?
                new ObjectParameter("ExpMonth", expMonth) :
                new ObjectParameter("ExpMonth", typeof(byte));
    
            var expYearParameter = expYear.HasValue ?
                new ObjectParameter("ExpYear", expYear) :
                new ObjectParameter("ExpYear", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modCreditCard", creditCardIDParameter, cardTypeParameter, cardNumberParameter, expMonthParameter, expYearParameter);
        }
    
        public virtual int PA_modUbicacion(Nullable<short> locationID, string nombre, Nullable<decimal> costo, Nullable<decimal> disponibilidad, Nullable<System.DateTime> fecModifica)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(short));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("Costo", costo) :
                new ObjectParameter("Costo", typeof(decimal));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(decimal));
    
            var fecModificaParameter = fecModifica.HasValue ?
                new ObjectParameter("FecModifica", fecModifica) :
                new ObjectParameter("FecModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modUbicacion", locationIDParameter, nombreParameter, costoParameter, disponibilidadParameter, fecModificaParameter);
        }
    
        public virtual ObjectResult<PA_recCreditCard_Result> PA_recCreditCard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recCreditCard_Result>("PA_recCreditCard");
        }
    
        public virtual ObjectResult<PA_recCreditCardXId_Result> PA_recCreditCardXId(Nullable<int> creditCardID)
        {
            var creditCardIDParameter = creditCardID.HasValue ?
                new ObjectParameter("CreditCardID", creditCardID) :
                new ObjectParameter("CreditCardID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recCreditCardXId_Result>("PA_recCreditCardXId", creditCardIDParameter);
        }
    
        public virtual ObjectResult<PA_recUbicacion_Result> PA_recUbicacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recUbicacion_Result>("PA_recUbicacion");
        }
    
        public virtual ObjectResult<PA_recUbicacionXId_Result> PA_recUbicacionXId(Nullable<short> locationID)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recUbicacionXId_Result>("PA_recUbicacionXId", locationIDParameter);
        }
    
        public virtual ObjectResult<recCountryRegions_Result> recCountryRegions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCountryRegions_Result>("recCountryRegions");
        }
    
        public virtual ObjectResult<recCountryRegionsxId_Result> recCountryRegionsxId(string countryRegionCode)
        {
            var countryRegionCodeParameter = countryRegionCode != null ?
                new ObjectParameter("CountryRegionCode", countryRegionCode) :
                new ObjectParameter("CountryRegionCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCountryRegionsxId_Result>("recCountryRegionsxId", countryRegionCodeParameter);
        }
    
        public virtual ObjectResult<recCulture_Result> recCulture()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCulture_Result>("recCulture");
        }
    
        public virtual ObjectResult<recCultureXId_Result> recCultureXId(string cultureID)
        {
            var cultureIDParameter = cultureID != null ?
                new ObjectParameter("CultureID", cultureID) :
                new ObjectParameter("CultureID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCultureXId_Result>("recCultureXId", cultureIDParameter);
        }
    
        public virtual ObjectResult<recCurrency_Result> recCurrency()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCurrency_Result>("recCurrency");
        }
    
        public virtual ObjectResult<recCurrencyxId_Result> recCurrencyxId(string currencyCode)
        {
            var currencyCodeParameter = currencyCode != null ?
                new ObjectParameter("CurrencyCode", currencyCode) :
                new ObjectParameter("CurrencyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recCurrencyxId_Result>("recCurrencyxId", currencyCodeParameter);
        }
    
        public virtual ObjectResult<recDepartment_Result> recDepartment()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recDepartment_Result>("recDepartment");
        }
    
        public virtual ObjectResult<recDepartmentXId_Result> recDepartmentXId(Nullable<int> departmentID)
        {
            var departmentIDParameter = departmentID.HasValue ?
                new ObjectParameter("DepartmentID", departmentID) :
                new ObjectParameter("DepartmentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recDepartmentXId_Result>("recDepartmentXId", departmentIDParameter);
        }
    
        public virtual ObjectResult<recSalesReason_Result> recSalesReason()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recSalesReason_Result>("recSalesReason");
        }
    
        public virtual ObjectResult<recSalesReasonxId_Result> recSalesReasonxId(Nullable<int> salesReasonID)
        {
            var salesReasonIDParameter = salesReasonID.HasValue ?
                new ObjectParameter("SalesReasonID", salesReasonID) :
                new ObjectParameter("SalesReasonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recSalesReasonxId_Result>("recSalesReasonxId", salesReasonIDParameter);
        }
    
        public virtual ObjectResult<recUnitMeasure_Result> recUnitMeasure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recUnitMeasure_Result>("recUnitMeasure");
        }
    
        public virtual ObjectResult<recUnitMeasurexId_Result> recUnitMeasurexId(string unitMeasureCode)
        {
            var unitMeasureCodeParameter = unitMeasureCode != null ?
                new ObjectParameter("UnitMeasureCode", unitMeasureCode) :
                new ObjectParameter("UnitMeasureCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<recUnitMeasurexId_Result>("recUnitMeasurexId", unitMeasureCodeParameter);
        }
    
        public virtual int uspAddOrderTrackingEvent(Nullable<int> salesOrderID, Nullable<int> trackingEventID, string eventDetails)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("SalesOrderID", salesOrderID) :
                new ObjectParameter("SalesOrderID", typeof(int));
    
            var trackingEventIDParameter = trackingEventID.HasValue ?
                new ObjectParameter("TrackingEventID", trackingEventID) :
                new ObjectParameter("TrackingEventID", typeof(int));
    
            var eventDetailsParameter = eventDetails != null ?
                new ObjectParameter("EventDetails", eventDetails) :
                new ObjectParameter("EventDetails", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspAddOrderTrackingEvent", salesOrderIDParameter, trackingEventIDParameter, eventDetailsParameter);
        }
    
        public virtual ObjectResult<uspGetBillOfMaterials_Result> uspGetBillOfMaterials(Nullable<int> startProductID, Nullable<System.DateTime> checkDate)
        {
            var startProductIDParameter = startProductID.HasValue ?
                new ObjectParameter("StartProductID", startProductID) :
                new ObjectParameter("StartProductID", typeof(int));
    
            var checkDateParameter = checkDate.HasValue ?
                new ObjectParameter("CheckDate", checkDate) :
                new ObjectParameter("CheckDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetBillOfMaterials_Result>("uspGetBillOfMaterials", startProductIDParameter, checkDateParameter);
        }
    
        public virtual ObjectResult<uspGetEmployeeManagers_Result> uspGetEmployeeManagers(Nullable<int> businessEntityID)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetEmployeeManagers_Result>("uspGetEmployeeManagers", businessEntityIDParameter);
        }
    
        public virtual ObjectResult<uspGetManagerEmployees_Result> uspGetManagerEmployees(Nullable<int> businessEntityID)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetManagerEmployees_Result>("uspGetManagerEmployees", businessEntityIDParameter);
        }
    
        public virtual ObjectResult<uspGetOrderTrackingBySalesOrderID_Result> uspGetOrderTrackingBySalesOrderID(Nullable<int> salesOrderID)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("SalesOrderID", salesOrderID) :
                new ObjectParameter("SalesOrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetOrderTrackingBySalesOrderID_Result>("uspGetOrderTrackingBySalesOrderID", salesOrderIDParameter);
        }
    
        public virtual ObjectResult<uspGetOrderTrackingByTrackingNumber_Result> uspGetOrderTrackingByTrackingNumber(string carrierTrackingNumber)
        {
            var carrierTrackingNumberParameter = carrierTrackingNumber != null ?
                new ObjectParameter("CarrierTrackingNumber", carrierTrackingNumber) :
                new ObjectParameter("CarrierTrackingNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetOrderTrackingByTrackingNumber_Result>("uspGetOrderTrackingByTrackingNumber", carrierTrackingNumberParameter);
        }
    
        public virtual ObjectResult<uspGetWhereUsedProductID_Result> uspGetWhereUsedProductID(Nullable<int> startProductID, Nullable<System.DateTime> checkDate)
        {
            var startProductIDParameter = startProductID.HasValue ?
                new ObjectParameter("StartProductID", startProductID) :
                new ObjectParameter("StartProductID", typeof(int));
    
            var checkDateParameter = checkDate.HasValue ?
                new ObjectParameter("CheckDate", checkDate) :
                new ObjectParameter("CheckDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetWhereUsedProductID_Result>("uspGetWhereUsedProductID", startProductIDParameter, checkDateParameter);
        }
    
        public virtual int uspLogError(ObjectParameter errorLogID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspLogError", errorLogID);
        }
    
        public virtual int uspPrintError()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspPrintError");
        }
    
        public virtual int uspSearchCandidateResumes(string searchString, Nullable<bool> useInflectional, Nullable<bool> useThesaurus, Nullable<int> language)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("searchString", searchString) :
                new ObjectParameter("searchString", typeof(string));
    
            var useInflectionalParameter = useInflectional.HasValue ?
                new ObjectParameter("useInflectional", useInflectional) :
                new ObjectParameter("useInflectional", typeof(bool));
    
            var useThesaurusParameter = useThesaurus.HasValue ?
                new ObjectParameter("useThesaurus", useThesaurus) :
                new ObjectParameter("useThesaurus", typeof(bool));
    
            var languageParameter = language.HasValue ?
                new ObjectParameter("language", language) :
                new ObjectParameter("language", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspSearchCandidateResumes", searchStringParameter, useInflectionalParameter, useThesaurusParameter, languageParameter);
        }
    
        public virtual int usp_DemoInitSeed(Nullable<int> items_per_order)
        {
            var items_per_orderParameter = items_per_order.HasValue ?
                new ObjectParameter("items_per_order", items_per_order) :
                new ObjectParameter("items_per_order", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DemoInitSeed", items_per_orderParameter);
        }
    
        public virtual int usp_DemoReset()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DemoReset");
        }
    
        public virtual ObjectResult<sp_GetEmployee_Person_Info_AsOf_Result> sp_GetEmployee_Person_Info_AsOf(Nullable<System.DateTime> asOf)
        {
            var asOfParameter = asOf.HasValue ?
                new ObjectParameter("asOf", asOf) :
                new ObjectParameter("asOf", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEmployee_Person_Info_AsOf_Result>("sp_GetEmployee_Person_Info_AsOf", asOfParameter);
        }
    
        public virtual int sp_UpdateEmployee_Temporal(Nullable<int> businessEntityID, string loginID, string jobTitle, string maritalStatus, string gender, Nullable<short> vacationHours, Nullable<short> sickLeaveHours)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            var loginIDParameter = loginID != null ?
                new ObjectParameter("LoginID", loginID) :
                new ObjectParameter("LoginID", typeof(string));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("JobTitle", jobTitle) :
                new ObjectParameter("JobTitle", typeof(string));
    
            var maritalStatusParameter = maritalStatus != null ?
                new ObjectParameter("MaritalStatus", maritalStatus) :
                new ObjectParameter("MaritalStatus", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var vacationHoursParameter = vacationHours.HasValue ?
                new ObjectParameter("VacationHours", vacationHours) :
                new ObjectParameter("VacationHours", typeof(short));
    
            var sickLeaveHoursParameter = sickLeaveHours.HasValue ?
                new ObjectParameter("SickLeaveHours", sickLeaveHours) :
                new ObjectParameter("SickLeaveHours", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateEmployee_Temporal", businessEntityIDParameter, loginIDParameter, jobTitleParameter, maritalStatusParameter, genderParameter, vacationHoursParameter, sickLeaveHoursParameter);
        }
    
        public virtual int uspUpdateEmployeeHireInfo(Nullable<int> businessEntityID, string jobTitle, Nullable<System.DateTime> hireDate, Nullable<System.DateTime> rateChangeDate, Nullable<decimal> rate, Nullable<byte> payFrequency, Nullable<bool> currentFlag)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("JobTitle", jobTitle) :
                new ObjectParameter("JobTitle", typeof(string));
    
            var hireDateParameter = hireDate.HasValue ?
                new ObjectParameter("HireDate", hireDate) :
                new ObjectParameter("HireDate", typeof(System.DateTime));
    
            var rateChangeDateParameter = rateChangeDate.HasValue ?
                new ObjectParameter("RateChangeDate", rateChangeDate) :
                new ObjectParameter("RateChangeDate", typeof(System.DateTime));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("Rate", rate) :
                new ObjectParameter("Rate", typeof(decimal));
    
            var payFrequencyParameter = payFrequency.HasValue ?
                new ObjectParameter("PayFrequency", payFrequency) :
                new ObjectParameter("PayFrequency", typeof(byte));
    
            var currentFlagParameter = currentFlag.HasValue ?
                new ObjectParameter("CurrentFlag", currentFlag) :
                new ObjectParameter("CurrentFlag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeHireInfo", businessEntityIDParameter, jobTitleParameter, hireDateParameter, rateChangeDateParameter, rateParameter, payFrequencyParameter, currentFlagParameter);
        }
    
        public virtual int uspUpdateEmployeeLogin(Nullable<int> businessEntityID, string loginID, string jobTitle, Nullable<System.DateTime> hireDate, Nullable<bool> currentFlag)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            var loginIDParameter = loginID != null ?
                new ObjectParameter("LoginID", loginID) :
                new ObjectParameter("LoginID", typeof(string));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("JobTitle", jobTitle) :
                new ObjectParameter("JobTitle", typeof(string));
    
            var hireDateParameter = hireDate.HasValue ?
                new ObjectParameter("HireDate", hireDate) :
                new ObjectParameter("HireDate", typeof(System.DateTime));
    
            var currentFlagParameter = currentFlag.HasValue ?
                new ObjectParameter("CurrentFlag", currentFlag) :
                new ObjectParameter("CurrentFlag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeLogin", businessEntityIDParameter, loginIDParameter, jobTitleParameter, hireDateParameter, currentFlagParameter);
        }
    
        public virtual int uspUpdateEmployeePersonalInfo(Nullable<int> businessEntityID, string nationalIDNumber, Nullable<System.DateTime> birthDate, string maritalStatus, string gender)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            var nationalIDNumberParameter = nationalIDNumber != null ?
                new ObjectParameter("NationalIDNumber", nationalIDNumber) :
                new ObjectParameter("NationalIDNumber", typeof(string));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            var maritalStatusParameter = maritalStatus != null ?
                new ObjectParameter("MaritalStatus", maritalStatus) :
                new ObjectParameter("MaritalStatus", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeePersonalInfo", businessEntityIDParameter, nationalIDNumberParameter, birthDateParameter, maritalStatusParameter, genderParameter);
        }
    
        public virtual int sp_DeletePerson_Temporal(Nullable<int> businessEntityID)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePerson_Temporal", businessEntityIDParameter);
        }
    
        public virtual int sp_UpdatePerson_Temporal(Nullable<int> businessEntityID, string personType, string title, string firstName, string middleName, string lastName, string suffix, Nullable<short> emailPromotion)
        {
            var businessEntityIDParameter = businessEntityID.HasValue ?
                new ObjectParameter("BusinessEntityID", businessEntityID) :
                new ObjectParameter("BusinessEntityID", typeof(int));
    
            var personTypeParameter = personType != null ?
                new ObjectParameter("PersonType", personType) :
                new ObjectParameter("PersonType", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var suffixParameter = suffix != null ?
                new ObjectParameter("Suffix", suffix) :
                new ObjectParameter("Suffix", typeof(string));
    
            var emailPromotionParameter = emailPromotion.HasValue ?
                new ObjectParameter("EmailPromotion", emailPromotion) :
                new ObjectParameter("EmailPromotion", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePerson_Temporal", businessEntityIDParameter, personTypeParameter, titleParameter, firstNameParameter, middleNameParameter, lastNameParameter, suffixParameter, emailPromotionParameter);
        }
    
        public virtual int usp_InsertSalesOrder_inmem(ObjectParameter salesOrderID, Nullable<System.DateTime> dueDate, Nullable<int> customerID, Nullable<int> billToAddressID, Nullable<int> shipToAddressID, Nullable<int> shipMethodID, Nullable<byte> status, Nullable<bool> onlineOrderFlag, string purchaseOrderNumber, string accountNumber, Nullable<int> salesPersonID, Nullable<int> territoryID, Nullable<int> creditCardID, string creditCardApprovalCode, Nullable<int> currencyRateID, string comment)
        {
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var billToAddressIDParameter = billToAddressID.HasValue ?
                new ObjectParameter("BillToAddressID", billToAddressID) :
                new ObjectParameter("BillToAddressID", typeof(int));
    
            var shipToAddressIDParameter = shipToAddressID.HasValue ?
                new ObjectParameter("ShipToAddressID", shipToAddressID) :
                new ObjectParameter("ShipToAddressID", typeof(int));
    
            var shipMethodIDParameter = shipMethodID.HasValue ?
                new ObjectParameter("ShipMethodID", shipMethodID) :
                new ObjectParameter("ShipMethodID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var onlineOrderFlagParameter = onlineOrderFlag.HasValue ?
                new ObjectParameter("OnlineOrderFlag", onlineOrderFlag) :
                new ObjectParameter("OnlineOrderFlag", typeof(bool));
    
            var purchaseOrderNumberParameter = purchaseOrderNumber != null ?
                new ObjectParameter("PurchaseOrderNumber", purchaseOrderNumber) :
                new ObjectParameter("PurchaseOrderNumber", typeof(string));
    
            var accountNumberParameter = accountNumber != null ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(string));
    
            var salesPersonIDParameter = salesPersonID.HasValue ?
                new ObjectParameter("SalesPersonID", salesPersonID) :
                new ObjectParameter("SalesPersonID", typeof(int));
    
            var territoryIDParameter = territoryID.HasValue ?
                new ObjectParameter("TerritoryID", territoryID) :
                new ObjectParameter("TerritoryID", typeof(int));
    
            var creditCardIDParameter = creditCardID.HasValue ?
                new ObjectParameter("CreditCardID", creditCardID) :
                new ObjectParameter("CreditCardID", typeof(int));
    
            var creditCardApprovalCodeParameter = creditCardApprovalCode != null ?
                new ObjectParameter("CreditCardApprovalCode", creditCardApprovalCode) :
                new ObjectParameter("CreditCardApprovalCode", typeof(string));
    
            var currencyRateIDParameter = currencyRateID.HasValue ?
                new ObjectParameter("CurrencyRateID", currencyRateID) :
                new ObjectParameter("CurrencyRateID", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertSalesOrder_inmem", salesOrderID, dueDateParameter, customerIDParameter, billToAddressIDParameter, shipToAddressIDParameter, shipMethodIDParameter, statusParameter, onlineOrderFlagParameter, purchaseOrderNumberParameter, accountNumberParameter, salesPersonIDParameter, territoryIDParameter, creditCardIDParameter, creditCardApprovalCodeParameter, currencyRateIDParameter, commentParameter);
        }
    
        public virtual int usp_InsertSalesOrder_ondisk(ObjectParameter salesOrderID, Nullable<System.DateTime> dueDate, Nullable<int> customerID, Nullable<int> billToAddressID, Nullable<int> shipToAddressID, Nullable<int> shipMethodID, Nullable<byte> status, Nullable<bool> onlineOrderFlag, string purchaseOrderNumber, string accountNumber, Nullable<int> salesPersonID, Nullable<int> territoryID, Nullable<int> creditCardID, string creditCardApprovalCode, Nullable<int> currencyRateID, string comment)
        {
            var dueDateParameter = dueDate.HasValue ?
                new ObjectParameter("DueDate", dueDate) :
                new ObjectParameter("DueDate", typeof(System.DateTime));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var billToAddressIDParameter = billToAddressID.HasValue ?
                new ObjectParameter("BillToAddressID", billToAddressID) :
                new ObjectParameter("BillToAddressID", typeof(int));
    
            var shipToAddressIDParameter = shipToAddressID.HasValue ?
                new ObjectParameter("ShipToAddressID", shipToAddressID) :
                new ObjectParameter("ShipToAddressID", typeof(int));
    
            var shipMethodIDParameter = shipMethodID.HasValue ?
                new ObjectParameter("ShipMethodID", shipMethodID) :
                new ObjectParameter("ShipMethodID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var onlineOrderFlagParameter = onlineOrderFlag.HasValue ?
                new ObjectParameter("OnlineOrderFlag", onlineOrderFlag) :
                new ObjectParameter("OnlineOrderFlag", typeof(bool));
    
            var purchaseOrderNumberParameter = purchaseOrderNumber != null ?
                new ObjectParameter("PurchaseOrderNumber", purchaseOrderNumber) :
                new ObjectParameter("PurchaseOrderNumber", typeof(string));
    
            var accountNumberParameter = accountNumber != null ?
                new ObjectParameter("AccountNumber", accountNumber) :
                new ObjectParameter("AccountNumber", typeof(string));
    
            var salesPersonIDParameter = salesPersonID.HasValue ?
                new ObjectParameter("SalesPersonID", salesPersonID) :
                new ObjectParameter("SalesPersonID", typeof(int));
    
            var territoryIDParameter = territoryID.HasValue ?
                new ObjectParameter("TerritoryID", territoryID) :
                new ObjectParameter("TerritoryID", typeof(int));
    
            var creditCardIDParameter = creditCardID.HasValue ?
                new ObjectParameter("CreditCardID", creditCardID) :
                new ObjectParameter("CreditCardID", typeof(int));
    
            var creditCardApprovalCodeParameter = creditCardApprovalCode != null ?
                new ObjectParameter("CreditCardApprovalCode", creditCardApprovalCode) :
                new ObjectParameter("CreditCardApprovalCode", typeof(string));
    
            var currencyRateIDParameter = currencyRateID.HasValue ?
                new ObjectParameter("CurrencyRateID", currencyRateID) :
                new ObjectParameter("CurrencyRateID", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertSalesOrder_ondisk", salesOrderID, dueDateParameter, customerIDParameter, billToAddressIDParameter, shipToAddressIDParameter, shipMethodIDParameter, statusParameter, onlineOrderFlagParameter, purchaseOrderNumberParameter, accountNumberParameter, salesPersonIDParameter, territoryIDParameter, creditCardIDParameter, creditCardApprovalCodeParameter, currencyRateIDParameter, commentParameter);
        }
    
        public virtual int usp_UpdateSalesOrderShipInfo_inmem(Nullable<int> salesOrderID, Nullable<System.DateTime> shipDate, string comment, Nullable<byte> status, Nullable<decimal> taxRate, Nullable<decimal> freight, string carrierTrackingNumber)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("SalesOrderID", salesOrderID) :
                new ObjectParameter("SalesOrderID", typeof(int));
    
            var shipDateParameter = shipDate.HasValue ?
                new ObjectParameter("ShipDate", shipDate) :
                new ObjectParameter("ShipDate", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var taxRateParameter = taxRate.HasValue ?
                new ObjectParameter("TaxRate", taxRate) :
                new ObjectParameter("TaxRate", typeof(decimal));
    
            var freightParameter = freight.HasValue ?
                new ObjectParameter("Freight", freight) :
                new ObjectParameter("Freight", typeof(decimal));
    
            var carrierTrackingNumberParameter = carrierTrackingNumber != null ?
                new ObjectParameter("CarrierTrackingNumber", carrierTrackingNumber) :
                new ObjectParameter("CarrierTrackingNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateSalesOrderShipInfo_inmem", salesOrderIDParameter, shipDateParameter, commentParameter, statusParameter, taxRateParameter, freightParameter, carrierTrackingNumberParameter);
        }
    
        public virtual int usp_UpdateSalesOrderShipInfo_native(Nullable<int> salesOrderID, Nullable<System.DateTime> shipDate, string comment, Nullable<byte> status, Nullable<decimal> taxRate, Nullable<decimal> freight, string carrierTrackingNumber)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("SalesOrderID", salesOrderID) :
                new ObjectParameter("SalesOrderID", typeof(int));
    
            var shipDateParameter = shipDate.HasValue ?
                new ObjectParameter("ShipDate", shipDate) :
                new ObjectParameter("ShipDate", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var taxRateParameter = taxRate.HasValue ?
                new ObjectParameter("TaxRate", taxRate) :
                new ObjectParameter("TaxRate", typeof(decimal));
    
            var freightParameter = freight.HasValue ?
                new ObjectParameter("Freight", freight) :
                new ObjectParameter("Freight", typeof(decimal));
    
            var carrierTrackingNumberParameter = carrierTrackingNumber != null ?
                new ObjectParameter("CarrierTrackingNumber", carrierTrackingNumber) :
                new ObjectParameter("CarrierTrackingNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateSalesOrderShipInfo_native", salesOrderIDParameter, shipDateParameter, commentParameter, statusParameter, taxRateParameter, freightParameter, carrierTrackingNumberParameter);
        }
    
        public virtual int usp_UpdateSalesOrderShipInfo_ondisk(Nullable<int> salesOrderID, Nullable<System.DateTime> shipDate, string comment, Nullable<byte> status, Nullable<decimal> taxRate, Nullable<decimal> freight, string carrierTrackingNumber)
        {
            var salesOrderIDParameter = salesOrderID.HasValue ?
                new ObjectParameter("SalesOrderID", salesOrderID) :
                new ObjectParameter("SalesOrderID", typeof(int));
    
            var shipDateParameter = shipDate.HasValue ?
                new ObjectParameter("ShipDate", shipDate) :
                new ObjectParameter("ShipDate", typeof(System.DateTime));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(byte));
    
            var taxRateParameter = taxRate.HasValue ?
                new ObjectParameter("TaxRate", taxRate) :
                new ObjectParameter("TaxRate", typeof(decimal));
    
            var freightParameter = freight.HasValue ?
                new ObjectParameter("Freight", freight) :
                new ObjectParameter("Freight", typeof(decimal));
    
            var carrierTrackingNumberParameter = carrierTrackingNumber != null ?
                new ObjectParameter("CarrierTrackingNumber", carrierTrackingNumber) :
                new ObjectParameter("CarrierTrackingNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateSalesOrderShipInfo_ondisk", salesOrderIDParameter, shipDateParameter, commentParameter, statusParameter, taxRateParameter, freightParameter, carrierTrackingNumberParameter);
        }
    }
}
