//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Citas
    {
        [Required(ErrorMessage ="El Numero de cita es requerido verifique...")]
        [Display(Name = "Numero de cita")]
        public int NumeroCita { get; set; }
        [Display(Name = "Codigo del cliente")]
        
        public Nullable<int> IDCliente { get; set; }
        [Display(Name = "Codigo de la Mascota")]
        public Nullable<int> IDMascota { get; set; }
        [Display(Name = "Fecha cita")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyy}")]
        public Nullable<System.DateTime> FechaCita { get; set; }
    }
}
