//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
      ///MaxLength(50, ErrorMessage ="")]
      ///MinLength(10, ErrorMessage ="")]
        [Required(ErrorMessage = "El ID cliente es requerido verifique...")]
        [Display(Name = "Codigo del cliente")]
        public int IDCliente { get; set; }
        [Display(Name = "Nombre del cliente")]
       [StringLength (50, MinimumLength = 10, ErrorMessage ="El nombre debe de tener 10 caracteres como minimo y 50 como maximo")]

        public string Nombre { get; set; }

        [Display(Name = "Primer Apellido")]
        public string PrimerApellido { get; set; }
        [Display(Name = "Segundo Apellido")]
        public string SegundoApellido { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        [Display(Name = "Correo ")]
        public string CorreoElectronico { get; set; }
    }
}
