//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvSalesReason {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvSalesReason.IsrvSalesReason")]
    public interface IsrvSalesReason {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/recSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/recSalesReason_ENTResponse")]
        System.Collections.Generic.List<Entidades.SalesReason> recSalesReason_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/recSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/recSalesReason_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SalesReason>> recSalesReason_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/recSalesReasonXId_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/recSalesReasonXId_ENTResponse")]
        Entidades.SalesReason recSalesReasonXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/recSalesReasonXId_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/recSalesReasonXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.SalesReason> recSalesReasonXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/insSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/insSalesReason_ENTResponse")]
        bool insSalesReason_ENT(Entidades.SalesReason pSalesReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/insSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/insSalesReason_ENTResponse")]
        System.Threading.Tasks.Task<bool> insSalesReason_ENTAsync(Entidades.SalesReason pSalesReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/modSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/modSalesReason_ENTResponse")]
        bool modSalesReason_ENT(Entidades.SalesReason pSalesReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/modSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/modSalesReason_ENTResponse")]
        System.Threading.Tasks.Task<bool> modSalesReason_ENTAsync(Entidades.SalesReason pSalesReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/delSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/delSalesReason_ENTResponse")]
        bool delSalesReason_ENT(Entidades.SalesReason pSalesReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvSalesReason/delSalesReason_ENT", ReplyAction="http://tempuri.org/IsrvSalesReason/delSalesReason_ENTResponse")]
        System.Threading.Tasks.Task<bool> delSalesReason_ENTAsync(Entidades.SalesReason pSalesReason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvSalesReasonChannel : mvcInterfazUsuario.srvSalesReason.IsrvSalesReason, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvSalesReasonClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvSalesReason.IsrvSalesReason>, mvcInterfazUsuario.srvSalesReason.IsrvSalesReason {
        
        public IsrvSalesReasonClient() {
        }
        
        public IsrvSalesReasonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvSalesReasonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSalesReasonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvSalesReasonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.SalesReason> recSalesReason_ENT() {
            return base.Channel.recSalesReason_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SalesReason>> recSalesReason_ENTAsync() {
            return base.Channel.recSalesReason_ENTAsync();
        }
        
        public Entidades.SalesReason recSalesReasonXId_ENT(int pId) {
            return base.Channel.recSalesReasonXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.SalesReason> recSalesReasonXId_ENTAsync(int pId) {
            return base.Channel.recSalesReasonXId_ENTAsync(pId);
        }
        
        public bool insSalesReason_ENT(Entidades.SalesReason pSalesReason) {
            return base.Channel.insSalesReason_ENT(pSalesReason);
        }
        
        public System.Threading.Tasks.Task<bool> insSalesReason_ENTAsync(Entidades.SalesReason pSalesReason) {
            return base.Channel.insSalesReason_ENTAsync(pSalesReason);
        }
        
        public bool modSalesReason_ENT(Entidades.SalesReason pSalesReason) {
            return base.Channel.modSalesReason_ENT(pSalesReason);
        }
        
        public System.Threading.Tasks.Task<bool> modSalesReason_ENTAsync(Entidades.SalesReason pSalesReason) {
            return base.Channel.modSalesReason_ENTAsync(pSalesReason);
        }
        
        public bool delSalesReason_ENT(Entidades.SalesReason pSalesReason) {
            return base.Channel.delSalesReason_ENT(pSalesReason);
        }
        
        public System.Threading.Tasks.Task<bool> delSalesReason_ENTAsync(Entidades.SalesReason pSalesReason) {
            return base.Channel.delSalesReason_ENTAsync(pSalesReason);
        }
    }
}
