//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvMascotas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvMascotas.IsrvMascotas")]
    public interface IsrvMascotas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/recMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/recMascotas_ENTResponse")]
        System.Collections.Generic.List<Entidades.Mascotas> recMascotas_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/recMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/recMascotas_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Mascotas>> recMascotas_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/recMascotasXId_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/recMascotasXId_ENTResponse")]
        Entidades.Mascotas recMascotasXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/recMascotasXId_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/recMascotasXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Mascotas> recMascotasXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/insMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/insMascotas_ENTResponse")]
        bool insMascotas_ENT(Entidades.Mascotas pMascotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/insMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/insMascotas_ENTResponse")]
        System.Threading.Tasks.Task<bool> insMascotas_ENTAsync(Entidades.Mascotas pMascotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/modMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/modMascotas_ENTResponse")]
        bool modMascotas_ENT(Entidades.Mascotas pMascotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/modMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/modMascotas_ENTResponse")]
        System.Threading.Tasks.Task<bool> modMascotas_ENTAsync(Entidades.Mascotas pMascotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/delMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/delMascotas_ENTResponse")]
        bool delMascotas_ENT(Entidades.Mascotas pMascotas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMascotas/delMascotas_ENT", ReplyAction="http://tempuri.org/IsrvMascotas/delMascotas_ENTResponse")]
        System.Threading.Tasks.Task<bool> delMascotas_ENTAsync(Entidades.Mascotas pMascotas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvMascotasChannel : mvcInterfazUsuario.srvMascotas.IsrvMascotas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvMascotasClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvMascotas.IsrvMascotas>, mvcInterfazUsuario.srvMascotas.IsrvMascotas {
        
        public IsrvMascotasClient() {
        }
        
        public IsrvMascotasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvMascotasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMascotasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMascotasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Mascotas> recMascotas_ENT() {
            return base.Channel.recMascotas_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Mascotas>> recMascotas_ENTAsync() {
            return base.Channel.recMascotas_ENTAsync();
        }
        
        public Entidades.Mascotas recMascotasXId_ENT(int pId) {
            return base.Channel.recMascotasXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Mascotas> recMascotasXId_ENTAsync(int pId) {
            return base.Channel.recMascotasXId_ENTAsync(pId);
        }
        
        public bool insMascotas_ENT(Entidades.Mascotas pMascotas) {
            return base.Channel.insMascotas_ENT(pMascotas);
        }
        
        public System.Threading.Tasks.Task<bool> insMascotas_ENTAsync(Entidades.Mascotas pMascotas) {
            return base.Channel.insMascotas_ENTAsync(pMascotas);
        }
        
        public bool modMascotas_ENT(Entidades.Mascotas pMascotas) {
            return base.Channel.modMascotas_ENT(pMascotas);
        }
        
        public System.Threading.Tasks.Task<bool> modMascotas_ENTAsync(Entidades.Mascotas pMascotas) {
            return base.Channel.modMascotas_ENTAsync(pMascotas);
        }
        
        public bool delMascotas_ENT(Entidades.Mascotas pMascotas) {
            return base.Channel.delMascotas_ENT(pMascotas);
        }
        
        public System.Threading.Tasks.Task<bool> delMascotas_ENTAsync(Entidades.Mascotas pMascotas) {
            return base.Channel.delMascotas_ENTAsync(pMascotas);
        }
    }
}
