//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvDiagnosticos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvDiagnosticos.IsrvDiagnosticos")]
    public interface IsrvDiagnosticos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/recDiagnosticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/recDiagnosticos_ENTResponse")]
        System.Collections.Generic.List<Entidades.Diagnósticos> recDiagnosticos_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/recDiagnosticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/recDiagnosticos_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Diagnósticos>> recDiagnosticos_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/recDiagnosticosXId_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/recDiagnosticosXId_ENTResponse")]
        Entidades.Diagnósticos recDiagnosticosXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/recDiagnosticosXId_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/recDiagnosticosXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Diagnósticos> recDiagnosticosXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/insDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/insDiagnósticos_ENTResponse")]
        bool insDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/insDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/insDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> insDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/modDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/modDiagnósticos_ENTResponse")]
        bool modDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/modDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/modDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> modDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/delDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/delDiagnósticos_ENTResponse")]
        bool delDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnosticos/delDiagnósticos_ENT", ReplyAction="http://tempuri.org/IsrvDiagnosticos/delDiagnósticos_ENTResponse")]
        System.Threading.Tasks.Task<bool> delDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvDiagnosticosChannel : mvcInterfazUsuario.srvDiagnosticos.IsrvDiagnosticos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvDiagnosticosClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvDiagnosticos.IsrvDiagnosticos>, mvcInterfazUsuario.srvDiagnosticos.IsrvDiagnosticos {
        
        public IsrvDiagnosticosClient() {
        }
        
        public IsrvDiagnosticosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvDiagnosticosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Diagnósticos> recDiagnosticos_ENT() {
            return base.Channel.recDiagnosticos_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Diagnósticos>> recDiagnosticos_ENTAsync() {
            return base.Channel.recDiagnosticos_ENTAsync();
        }
        
        public Entidades.Diagnósticos recDiagnosticosXId_ENT(int pId) {
            return base.Channel.recDiagnosticosXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Diagnósticos> recDiagnosticosXId_ENTAsync(int pId) {
            return base.Channel.recDiagnosticosXId_ENTAsync(pId);
        }
        
        public bool insDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.insDiagnósticos_ENT(pDiagnosticos);
        }
        
        public System.Threading.Tasks.Task<bool> insDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.insDiagnósticos_ENTAsync(pDiagnosticos);
        }
        
        public bool modDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.modDiagnósticos_ENT(pDiagnosticos);
        }
        
        public System.Threading.Tasks.Task<bool> modDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.modDiagnósticos_ENTAsync(pDiagnosticos);
        }
        
        public bool delDiagnósticos_ENT(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.delDiagnósticos_ENT(pDiagnosticos);
        }
        
        public System.Threading.Tasks.Task<bool> delDiagnósticos_ENTAsync(Entidades.Diagnósticos pDiagnosticos) {
            return base.Channel.delDiagnósticos_ENTAsync(pDiagnosticos);
        }
    }
}
